---
# vim: set ft=ansible:

- name: Make sure Bastion VM isn't running
  ansible.builtin.command: virsh shutdown ocp4-bastion

- name: Create temporary users SSH public key file
  ansible.builtin.lineinfile:
    path: /tmp/user-key.pub
    line: "{{ ocp4_aio_ssh_key }}"
    create: true
    mode: "0664"

- name: Inject users SSH key into Bastion VM for Ansible
  ansible.builtin.command: >
    virt-customize -a /var/lib/libvirt/images/ocp4-bastion.qcow2 --selinux-relabel
    --ssh-inject root:file:/root/.ssh/id_rsa.pub
    --ssh-inject root:file:/tmp/user-key.pub
  register: result
  until: result is succeeded
  retries: 3
  delay: 30

- name: Check if we've done this stage before with existing image
  ansible.builtin.stat:
    path: /var/lib/libvirt/images/centos8-kvm-cnv.qcow2
  register: centos8_cnv

- name: Make a copy of the centos8-kvm image
  when: not centos8_cnv.stat.exists
  ansible.builtin.copy:
    remote_src: true
    src: /var/lib/libvirt/images/centos8-kvm.qcow2
    dest: /var/lib/libvirt/images/centos8-kvm-cnv.qcow2
    mode: "0664"

- name: Set the root password on the centos8-kvm-cnv image
  when: not centos8_cnv.stat.exists
  ansible.builtin.command: >
    virt-customize -a /var/lib/libvirt/images/centos8-kvm-cnv.qcow2 --root-password password:{{ ocp4_aio_root_password }}

- name: Start Bastion virtual machine
  ansible.builtin.shell: virsh start ocp4-bastion
